/*
 * Copyright (c) 2024 Huawei Device Co., Ltd. All rights reserved
 * Use of this source code is governed by a MIT license that can be
 * found in the LICENSE file.
 */

module.exports.makeCryptographicModuleTemplateHarmony = (key) => {
  return `// this is autogenerated, dont change within it
#pragma once

#include <string>

static std::string const privateKey = "${key}"; 
  `;
};