module.exports.makeCryptographicModuleTemplateHarmony = (key) => {
  return `// this is autogenerated, dont change within it
#pragma once

#include <string>

static std::string const privateKey = "${key}"; 
  `;
};